# Generated by Django 5.1.3 on 2024-12-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='user', max_length=100, null=True),
        ),
    ]
