# Generated by Django 5.1.3 on 2024-12-05 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_follow_delete_follower'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'following')},
        ),
    ]
