# Generated by Django 5.1.3 on 2024-12-05 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_follow_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_followed',
        ),
    ]
